"""GitHubPRAdapter — dry-run only in v1.

Real PR creation requires a GH_TOKEN with `pull_requests:write`; v1 prints
the title + body + diff that WOULD be sent. Intended for the software_eng
vertical (artifact.fields["patch"]).
"""

from __future__ import annotations

import os
from typing import Any

from truman.deploy.base import DeployResult


class GitHubPRAdapter:
    name = "github_pr"

    def is_live(self) -> bool:
        return bool(os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN"))

    def export(self, run: Any, goal: Any, dry_run: bool = True) -> DeployResult:
        artifact = run.final_artifact
        fields = artifact.fields or {}
        repo = (goal.scene or {}).get("repo", "<unset>")
        title = fields.get("summary") or artifact.rationale or "Truman delivered patch"
        files = fields.get("files_changed", [])
        patch = fields.get("patch", artifact.content)
        body = (
            f"Auto-generated by Truman ({goal.vertical}).\n\n"
            f"**Goal**: {goal.goal}\n\n"
            f"**Files**: {', '.join(files) if files else '—'}\n\n"
            f"**Score**: {run.final_verdict.score:.3f} / threshold {goal.threshold:.2f}\n\n"
            f"```python\n{patch}\n```"
        )
        return DeployResult(
            target=self.name,
            dry_run=True,
            payload_summary=f"[dry-run] would create PR on {repo}: {title}",
            extra={
                "repo": repo, "title": title, "body": body, "files": files,
                "is_live_capable": self.is_live(),
            },
        )
